#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 115
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 74
#define ALIAS_COUNT 3
#define TOKEN_COUNT 29
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 5
#define PRODUCTION_ID_COUNT 4

enum ts_symbol_identifiers {
  anon_sym_COLON = 1,
  anon_sym_SEMI = 2,
  anon_sym_var = 3,
  anon_sym_EQ = 4,
  anon_sym_AMP = 5,
  anon_sym_LPAREN = 6,
  anon_sym_RPAREN = 7,
  anon_sym_COMMA = 8,
  anon_sym_SQUOTE = 9,
  anon_sym_DQUOTE = 10,
  aux_sym_hexdigit_token1 = 11,
  aux_sym_hexdigit_token2 = 12,
  sym_letter = 13,
  sym_digit = 14,
  sym_zerotoseven = 15,
  anon_sym_BSLASH = 16,
  anon_sym_v = 17,
  anon_sym_a = 18,
  anon_sym_b = 19,
  anon_sym_t = 20,
  anon_sym_n = 21,
  anon_sym_f = 22,
  anon_sym_r = 23,
  anon_sym_DOLLAR = 24,
  anon_sym_LT = 25,
  aux_sym_octalescape_token1 = 26,
  anon_sym_BSLASHu = 27,
  sym_any_character = 28,
  sym_source_file = 29,
  sym_typeannotation = 30,
  sym_statement = 31,
  sym_localvarstatement = 32,
  sym_assignmentormethodcall = 33,
  sym_classorinterfacetype = 34,
  sym_type = 35,
  sym_typeliteral = 36,
  sym_typeliteralexpr = 37,
  sym_expression = 38,
  sym_conditionalexpr = 39,
  sym_conditionalorexpr = 40,
  sym_conditionalandexpr = 41,
  sym_bitwiseorexpr = 42,
  sym_bitwisexorexpr = 43,
  sym_bitwiseandexpr = 44,
  sym_equalityexpr = 45,
  sym_relationalexpr = 46,
  sym_intervalexpr = 47,
  sym_bitshiftexpr = 48,
  sym_additiveexpr = 49,
  sym_multiplicativeexpr = 50,
  sym_typeasexpr = 51,
  sym_unaryexpr = 52,
  sym_unaryexprnotplusminus = 53,
  sym_primaryexpr = 54,
  sym_parenthexpr = 55,
  sym_arguments = 56,
  sym_argexpression = 57,
  sym_namedargexpression = 58,
  sym_indirectmemberaccessone = 59,
  sym_literal = 60,
  sym_idclassorinterfacetype = 61,
  sym_id = 62,
  sym_ident = 63,
  sym_stringliteral = 64,
  sym_hexdigit = 65,
  sym_escapesequence = 66,
  sym_octalescape = 67,
  sym_unicodeescape = 68,
  aux_sym_source_file_repeat1 = 69,
  aux_sym_assignmentormethodcall_repeat1 = 70,
  aux_sym_arguments_repeat1 = 71,
  aux_sym_ident_repeat1 = 72,
  aux_sym_stringliteral_repeat1 = 73,
  alias_sym_pat_0_3 = 74,
  alias_sym_pat_dcaf70f = 75,
  alias_sym_pat_dd18f70 = 76,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_COLON] = ":",
  [anon_sym_SEMI] = ";",
  [anon_sym_var] = "var",
  [anon_sym_EQ] = "=",
  [anon_sym_AMP] = "&",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_COMMA] = ", ",
  [anon_sym_SQUOTE] = "'",
  [anon_sym_DQUOTE] = "\"",
  [aux_sym_hexdigit_token1] = "hexdigit_token1",
  [aux_sym_hexdigit_token2] = "hexdigit_token2",
  [sym_letter] = "letter",
  [sym_digit] = "digit",
  [sym_zerotoseven] = "zerotoseven",
  [anon_sym_BSLASH] = "\\",
  [anon_sym_v] = "v",
  [anon_sym_a] = "a",
  [anon_sym_b] = "b",
  [anon_sym_t] = "t",
  [anon_sym_n] = "n",
  [anon_sym_f] = "f",
  [anon_sym_r] = "r",
  [anon_sym_DOLLAR] = "$",
  [anon_sym_LT] = "<",
  [aux_sym_octalescape_token1] = "octalescape_token1",
  [anon_sym_BSLASHu] = "\\u",
  [sym_any_character] = "any_character",
  [sym_source_file] = "source_file",
  [sym_typeannotation] = "typeannotation",
  [sym_statement] = "statement",
  [sym_localvarstatement] = "localvarstatement",
  [sym_assignmentormethodcall] = "assignmentormethodcall",
  [sym_classorinterfacetype] = "classorinterfacetype",
  [sym_type] = "type",
  [sym_typeliteral] = "typeliteral",
  [sym_typeliteralexpr] = "typeliteralexpr",
  [sym_expression] = "expression",
  [sym_conditionalexpr] = "conditionalexpr",
  [sym_conditionalorexpr] = "conditionalorexpr",
  [sym_conditionalandexpr] = "conditionalandexpr",
  [sym_bitwiseorexpr] = "bitwiseorexpr",
  [sym_bitwisexorexpr] = "bitwisexorexpr",
  [sym_bitwiseandexpr] = "bitwiseandexpr",
  [sym_equalityexpr] = "equalityexpr",
  [sym_relationalexpr] = "relationalexpr",
  [sym_intervalexpr] = "intervalexpr",
  [sym_bitshiftexpr] = "bitshiftexpr",
  [sym_additiveexpr] = "additiveexpr",
  [sym_multiplicativeexpr] = "multiplicativeexpr",
  [sym_typeasexpr] = "typeasexpr",
  [sym_unaryexpr] = "unaryexpr",
  [sym_unaryexprnotplusminus] = "unaryexprnotplusminus",
  [sym_primaryexpr] = "primaryexpr",
  [sym_parenthexpr] = "parenthexpr",
  [sym_arguments] = "arguments",
  [sym_argexpression] = "argexpression",
  [sym_namedargexpression] = "namedargexpression",
  [sym_indirectmemberaccessone] = "indirectmemberaccessone",
  [sym_literal] = "literal",
  [sym_idclassorinterfacetype] = "idclassorinterfacetype",
  [sym_id] = "id",
  [sym_ident] = "ident",
  [sym_stringliteral] = "stringliteral",
  [sym_hexdigit] = "hexdigit",
  [sym_escapesequence] = "escapesequence",
  [sym_octalescape] = "octalescape",
  [sym_unicodeescape] = "unicodeescape",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_assignmentormethodcall_repeat1] = "assignmentormethodcall_repeat1",
  [aux_sym_arguments_repeat1] = "arguments_repeat1",
  [aux_sym_ident_repeat1] = "ident_repeat1",
  [aux_sym_stringliteral_repeat1] = "stringliteral_repeat1",
  [alias_sym_pat_0_3] = "pat_0_3",
  [alias_sym_pat_dcaf70f] = "pat_dcaf70f",
  [alias_sym_pat_dd18f70] = "pat_dd18f70",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_SEMI] = anon_sym_SEMI,
  [anon_sym_var] = anon_sym_var,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_AMP] = anon_sym_AMP,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_SQUOTE] = anon_sym_SQUOTE,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [aux_sym_hexdigit_token1] = aux_sym_hexdigit_token1,
  [aux_sym_hexdigit_token2] = aux_sym_hexdigit_token2,
  [sym_letter] = sym_letter,
  [sym_digit] = sym_digit,
  [sym_zerotoseven] = sym_zerotoseven,
  [anon_sym_BSLASH] = anon_sym_BSLASH,
  [anon_sym_v] = anon_sym_v,
  [anon_sym_a] = anon_sym_a,
  [anon_sym_b] = anon_sym_b,
  [anon_sym_t] = anon_sym_t,
  [anon_sym_n] = anon_sym_n,
  [anon_sym_f] = anon_sym_f,
  [anon_sym_r] = anon_sym_r,
  [anon_sym_DOLLAR] = anon_sym_DOLLAR,
  [anon_sym_LT] = anon_sym_LT,
  [aux_sym_octalescape_token1] = aux_sym_octalescape_token1,
  [anon_sym_BSLASHu] = anon_sym_BSLASHu,
  [sym_any_character] = sym_any_character,
  [sym_source_file] = sym_source_file,
  [sym_typeannotation] = sym_typeannotation,
  [sym_statement] = sym_statement,
  [sym_localvarstatement] = sym_localvarstatement,
  [sym_assignmentormethodcall] = sym_assignmentormethodcall,
  [sym_classorinterfacetype] = sym_classorinterfacetype,
  [sym_type] = sym_type,
  [sym_typeliteral] = sym_typeliteral,
  [sym_typeliteralexpr] = sym_typeliteralexpr,
  [sym_expression] = sym_expression,
  [sym_conditionalexpr] = sym_conditionalexpr,
  [sym_conditionalorexpr] = sym_conditionalorexpr,
  [sym_conditionalandexpr] = sym_conditionalandexpr,
  [sym_bitwiseorexpr] = sym_bitwiseorexpr,
  [sym_bitwisexorexpr] = sym_bitwisexorexpr,
  [sym_bitwiseandexpr] = sym_bitwiseandexpr,
  [sym_equalityexpr] = sym_equalityexpr,
  [sym_relationalexpr] = sym_relationalexpr,
  [sym_intervalexpr] = sym_intervalexpr,
  [sym_bitshiftexpr] = sym_bitshiftexpr,
  [sym_additiveexpr] = sym_additiveexpr,
  [sym_multiplicativeexpr] = sym_multiplicativeexpr,
  [sym_typeasexpr] = sym_typeasexpr,
  [sym_unaryexpr] = sym_unaryexpr,
  [sym_unaryexprnotplusminus] = sym_unaryexprnotplusminus,
  [sym_primaryexpr] = sym_primaryexpr,
  [sym_parenthexpr] = sym_parenthexpr,
  [sym_arguments] = sym_arguments,
  [sym_argexpression] = sym_argexpression,
  [sym_namedargexpression] = sym_namedargexpression,
  [sym_indirectmemberaccessone] = sym_indirectmemberaccessone,
  [sym_literal] = sym_literal,
  [sym_idclassorinterfacetype] = sym_idclassorinterfacetype,
  [sym_id] = sym_id,
  [sym_ident] = sym_ident,
  [sym_stringliteral] = sym_stringliteral,
  [sym_hexdigit] = sym_hexdigit,
  [sym_escapesequence] = sym_escapesequence,
  [sym_octalescape] = sym_octalescape,
  [sym_unicodeescape] = sym_unicodeescape,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_assignmentormethodcall_repeat1] = aux_sym_assignmentormethodcall_repeat1,
  [aux_sym_arguments_repeat1] = aux_sym_arguments_repeat1,
  [aux_sym_ident_repeat1] = aux_sym_ident_repeat1,
  [aux_sym_stringliteral_repeat1] = aux_sym_stringliteral_repeat1,
  [alias_sym_pat_0_3] = alias_sym_pat_0_3,
  [alias_sym_pat_dcaf70f] = alias_sym_pat_dcaf70f,
  [alias_sym_pat_dd18f70] = alias_sym_pat_dd18f70,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SEMI] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_var] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_AMP] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SQUOTE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_hexdigit_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_hexdigit_token2] = {
    .visible = false,
    .named = false,
  },
  [sym_letter] = {
    .visible = true,
    .named = true,
  },
  [sym_digit] = {
    .visible = true,
    .named = true,
  },
  [sym_zerotoseven] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_BSLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_v] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_a] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_b] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_t] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_n] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_f] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_r] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOLLAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_octalescape_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_BSLASHu] = {
    .visible = true,
    .named = false,
  },
  [sym_any_character] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_typeannotation] = {
    .visible = true,
    .named = true,
  },
  [sym_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_localvarstatement] = {
    .visible = true,
    .named = true,
  },
  [sym_assignmentormethodcall] = {
    .visible = true,
    .named = true,
  },
  [sym_classorinterfacetype] = {
    .visible = true,
    .named = true,
  },
  [sym_type] = {
    .visible = true,
    .named = true,
  },
  [sym_typeliteral] = {
    .visible = true,
    .named = true,
  },
  [sym_typeliteralexpr] = {
    .visible = true,
    .named = true,
  },
  [sym_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_conditionalexpr] = {
    .visible = true,
    .named = true,
  },
  [sym_conditionalorexpr] = {
    .visible = true,
    .named = true,
  },
  [sym_conditionalandexpr] = {
    .visible = true,
    .named = true,
  },
  [sym_bitwiseorexpr] = {
    .visible = true,
    .named = true,
  },
  [sym_bitwisexorexpr] = {
    .visible = true,
    .named = true,
  },
  [sym_bitwiseandexpr] = {
    .visible = true,
    .named = true,
  },
  [sym_equalityexpr] = {
    .visible = true,
    .named = true,
  },
  [sym_relationalexpr] = {
    .visible = true,
    .named = true,
  },
  [sym_intervalexpr] = {
    .visible = true,
    .named = true,
  },
  [sym_bitshiftexpr] = {
    .visible = true,
    .named = true,
  },
  [sym_additiveexpr] = {
    .visible = true,
    .named = true,
  },
  [sym_multiplicativeexpr] = {
    .visible = true,
    .named = true,
  },
  [sym_typeasexpr] = {
    .visible = true,
    .named = true,
  },
  [sym_unaryexpr] = {
    .visible = true,
    .named = true,
  },
  [sym_unaryexprnotplusminus] = {
    .visible = true,
    .named = true,
  },
  [sym_primaryexpr] = {
    .visible = true,
    .named = true,
  },
  [sym_parenthexpr] = {
    .visible = true,
    .named = true,
  },
  [sym_arguments] = {
    .visible = true,
    .named = true,
  },
  [sym_argexpression] = {
    .visible = true,
    .named = true,
  },
  [sym_namedargexpression] = {
    .visible = true,
    .named = true,
  },
  [sym_indirectmemberaccessone] = {
    .visible = true,
    .named = true,
  },
  [sym_literal] = {
    .visible = true,
    .named = true,
  },
  [sym_idclassorinterfacetype] = {
    .visible = true,
    .named = true,
  },
  [sym_id] = {
    .visible = true,
    .named = true,
  },
  [sym_ident] = {
    .visible = true,
    .named = true,
  },
  [sym_stringliteral] = {
    .visible = true,
    .named = true,
  },
  [sym_hexdigit] = {
    .visible = true,
    .named = true,
  },
  [sym_escapesequence] = {
    .visible = true,
    .named = true,
  },
  [sym_octalescape] = {
    .visible = true,
    .named = true,
  },
  [sym_unicodeescape] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_assignmentormethodcall_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_arguments_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_ident_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_stringliteral_repeat1] = {
    .visible = false,
    .named = false,
  },
  [alias_sym_pat_0_3] = {
    .visible = true,
    .named = true,
  },
  [alias_sym_pat_dcaf70f] = {
    .visible = true,
    .named = true,
  },
  [alias_sym_pat_dd18f70] = {
    .visible = true,
    .named = true,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
  [1] = {
    [0] = alias_sym_pat_dcaf70f,
  },
  [2] = {
    [0] = alias_sym_pat_dd18f70,
  },
  [3] = {
    [1] = alias_sym_pat_0_3,
  },
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 10,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 47,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 13,
  [64] = 12,
  [65] = 14,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 69,
  [71] = 68,
  [72] = 72,
  [73] = 73,
  [74] = 74,
  [75] = 75,
  [76] = 76,
  [77] = 77,
  [78] = 78,
  [79] = 79,
  [80] = 79,
  [81] = 81,
  [82] = 75,
  [83] = 83,
  [84] = 84,
  [85] = 85,
  [86] = 76,
  [87] = 74,
  [88] = 77,
  [89] = 83,
  [90] = 84,
  [91] = 85,
  [92] = 81,
  [93] = 72,
  [94] = 73,
  [95] = 78,
  [96] = 96,
  [97] = 97,
  [98] = 84,
  [99] = 99,
  [100] = 85,
  [101] = 101,
  [102] = 102,
  [103] = 35,
  [104] = 83,
  [105] = 105,
  [106] = 106,
  [107] = 107,
  [108] = 108,
  [109] = 109,
  [110] = 110,
  [111] = 109,
  [112] = 112,
  [113] = 110,
  [114] = 114,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(13);
      ADVANCE_MAP(
        '"', 23,
        '$', 40,
        '&', 18,
        '\'', 22,
        '(', 19,
        ')', 20,
        ',', 5,
        ':', 14,
        ';', 15,
        '<', 41,
        '=', 17,
        '\\', 32,
        'a', 34,
        'b', 35,
        'f', 38,
        'n', 37,
        'r', 39,
        't', 36,
        'v', 33,
        '8', 28,
        '9', 28,
      );
      if (('c' <= lookahead && lookahead <= 'e')) ADVANCE(25);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('A' <= lookahead && lookahead <= 'F')) ADVANCE(24);
      if (('0' <= lookahead && lookahead <= '7')) ADVANCE(28);
      if (('G' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('g' <= lookahead && lookahead <= 'z')) ADVANCE(26);
      END_STATE();
    case 1:
      if (lookahead == '\n') SKIP(1);
      if (lookahead == '\'') ADVANCE(22);
      if (lookahead == '\\') ADVANCE(32);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(47);
      if (lookahead != 0) ADVANCE(44);
      END_STATE();
    case 2:
      if (lookahead == '\n') SKIP(2);
      if (lookahead == '"') ADVANCE(23);
      if (lookahead == '\\') ADVANCE(32);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(45);
      if (lookahead != 0) ADVANCE(44);
      END_STATE();
    case 3:
      if (lookahead == '\n') SKIP(3);
      if (lookahead == '\'') ADVANCE(22);
      if (lookahead == '\\') ADVANCE(32);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(48);
      if (('0' <= lookahead && lookahead <= '7')) ADVANCE(29);
      if (lookahead != 0) ADVANCE(44);
      END_STATE();
    case 4:
      if (lookahead == '\n') SKIP(4);
      if (lookahead == '"') ADVANCE(23);
      if (lookahead == '\\') ADVANCE(32);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(46);
      if (('0' <= lookahead && lookahead <= '7')) ADVANCE(29);
      if (lookahead != 0) ADVANCE(44);
      END_STATE();
    case 5:
      if (lookahead == ' ') ADVANCE(21);
      END_STATE();
    case 6:
      ADVANCE_MAP(
        '"', 23,
        '$', 40,
        '\'', 22,
        '0', 30,
        '<', 41,
        '\\', 31,
        'a', 34,
        'b', 35,
        'f', 38,
        'n', 37,
        'r', 39,
        't', 36,
        'v', 33,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(6);
      if (('1' <= lookahead && lookahead <= '7')) ADVANCE(29);
      END_STATE();
    case 7:
      if (lookahead == '"') ADVANCE(23);
      if (lookahead == '&') ADVANCE(18);
      if (lookahead == '\'') ADVANCE(22);
      if (lookahead == ')') ADVANCE(20);
      if (lookahead == ',') ADVANCE(5);
      if (lookahead == ':') ADVANCE(14);
      if (lookahead == '=') ADVANCE(17);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(7);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(28);
      if (lookahead == '$' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(26);
      END_STATE();
    case 8:
      if (lookahead == '3') ADVANCE(42);
      END_STATE();
    case 9:
      if (lookahead == 'r') ADVANCE(16);
      END_STATE();
    case 10:
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(10);
      if (('A' <= lookahead && lookahead <= 'F')) ADVANCE(24);
      if (('a' <= lookahead && lookahead <= 'f')) ADVANCE(25);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(28);
      END_STATE();
    case 11:
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(11);
      if (('0' <= lookahead && lookahead <= '7')) ADVANCE(29);
      END_STATE();
    case 12:
      if (eof) ADVANCE(13);
      ADVANCE_MAP(
        '"', 23,
        '&', 18,
        '\'', 22,
        '(', 19,
        ')', 20,
        ',', 5,
        ':', 14,
        ';', 15,
        '=', 17,
        'v', 27,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(12);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(28);
      if (lookahead == '$' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(26);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(anon_sym_SEMI);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_var);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_AMP);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_SQUOTE);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(aux_sym_hexdigit_token1);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(aux_sym_hexdigit_token2);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(sym_letter);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(sym_letter);
      if (lookahead == 'a') ADVANCE(9);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(sym_digit);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(sym_zerotoseven);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(sym_zerotoseven);
      if (lookahead == '-') ADVANCE(8);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(anon_sym_BSLASH);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(anon_sym_BSLASH);
      if (lookahead == 'u') ADVANCE(43);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(anon_sym_v);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(anon_sym_a);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(anon_sym_b);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(anon_sym_t);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(anon_sym_n);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(anon_sym_f);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(anon_sym_r);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(anon_sym_DOLLAR);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(anon_sym_LT);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(aux_sym_octalescape_token1);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(anon_sym_BSLASHu);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(sym_any_character);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(sym_any_character);
      if (lookahead == '"') ADVANCE(23);
      if (lookahead == '\\') ADVANCE(32);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(45);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(44);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(sym_any_character);
      if (lookahead == '"') ADVANCE(23);
      if (lookahead == '\\') ADVANCE(32);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(46);
      if (('0' <= lookahead && lookahead <= '7')) ADVANCE(29);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(44);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(sym_any_character);
      if (lookahead == '\'') ADVANCE(22);
      if (lookahead == '\\') ADVANCE(32);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(47);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(44);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(sym_any_character);
      if (lookahead == '\'') ADVANCE(22);
      if (lookahead == '\\') ADVANCE(32);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(48);
      if (('0' <= lookahead && lookahead <= '7')) ADVANCE(29);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(44);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 12},
  [2] = {.lex_state = 7},
  [3] = {.lex_state = 7},
  [4] = {.lex_state = 7},
  [5] = {.lex_state = 7},
  [6] = {.lex_state = 7},
  [7] = {.lex_state = 7},
  [8] = {.lex_state = 12},
  [9] = {.lex_state = 12},
  [10] = {.lex_state = 6},
  [11] = {.lex_state = 6},
  [12] = {.lex_state = 12},
  [13] = {.lex_state = 12},
  [14] = {.lex_state = 12},
  [15] = {.lex_state = 12},
  [16] = {.lex_state = 12},
  [17] = {.lex_state = 12},
  [18] = {.lex_state = 12},
  [19] = {.lex_state = 12},
  [20] = {.lex_state = 12},
  [21] = {.lex_state = 12},
  [22] = {.lex_state = 12},
  [23] = {.lex_state = 12},
  [24] = {.lex_state = 12},
  [25] = {.lex_state = 12},
  [26] = {.lex_state = 12},
  [27] = {.lex_state = 12},
  [28] = {.lex_state = 12},
  [29] = {.lex_state = 12},
  [30] = {.lex_state = 12},
  [31] = {.lex_state = 12},
  [32] = {.lex_state = 12},
  [33] = {.lex_state = 12},
  [34] = {.lex_state = 12},
  [35] = {.lex_state = 12},
  [36] = {.lex_state = 12},
  [37] = {.lex_state = 12},
  [38] = {.lex_state = 12},
  [39] = {.lex_state = 12},
  [40] = {.lex_state = 12},
  [41] = {.lex_state = 12},
  [42] = {.lex_state = 12},
  [43] = {.lex_state = 12},
  [44] = {.lex_state = 12},
  [45] = {.lex_state = 12},
  [46] = {.lex_state = 1},
  [47] = {.lex_state = 1},
  [48] = {.lex_state = 2},
  [49] = {.lex_state = 1},
  [50] = {.lex_state = 12},
  [51] = {.lex_state = 2},
  [52] = {.lex_state = 2},
  [53] = {.lex_state = 12},
  [54] = {.lex_state = 12},
  [55] = {.lex_state = 12},
  [56] = {.lex_state = 12},
  [57] = {.lex_state = 12},
  [58] = {.lex_state = 12},
  [59] = {.lex_state = 12},
  [60] = {.lex_state = 12},
  [61] = {.lex_state = 12},
  [62] = {.lex_state = 12},
  [63] = {.lex_state = 7},
  [64] = {.lex_state = 7},
  [65] = {.lex_state = 7},
  [66] = {.lex_state = 12},
  [67] = {.lex_state = 7},
  [68] = {.lex_state = 3},
  [69] = {.lex_state = 7},
  [70] = {.lex_state = 7},
  [71] = {.lex_state = 4},
  [72] = {.lex_state = 10},
  [73] = {.lex_state = 10},
  [74] = {.lex_state = 1},
  [75] = {.lex_state = 1},
  [76] = {.lex_state = 1},
  [77] = {.lex_state = 1},
  [78] = {.lex_state = 10},
  [79] = {.lex_state = 2},
  [80] = {.lex_state = 1},
  [81] = {.lex_state = 10},
  [82] = {.lex_state = 2},
  [83] = {.lex_state = 1},
  [84] = {.lex_state = 1},
  [85] = {.lex_state = 1},
  [86] = {.lex_state = 2},
  [87] = {.lex_state = 2},
  [88] = {.lex_state = 2},
  [89] = {.lex_state = 2},
  [90] = {.lex_state = 2},
  [91] = {.lex_state = 2},
  [92] = {.lex_state = 10},
  [93] = {.lex_state = 10},
  [94] = {.lex_state = 10},
  [95] = {.lex_state = 10},
  [96] = {.lex_state = 0},
  [97] = {.lex_state = 7},
  [98] = {.lex_state = 10},
  [99] = {.lex_state = 7},
  [100] = {.lex_state = 10},
  [101] = {.lex_state = 0},
  [102] = {.lex_state = 0},
  [103] = {.lex_state = 0},
  [104] = {.lex_state = 10},
  [105] = {.lex_state = 0},
  [106] = {.lex_state = 0},
  [107] = {.lex_state = 0},
  [108] = {.lex_state = 0},
  [109] = {.lex_state = 11},
  [110] = {.lex_state = 11},
  [111] = {.lex_state = 11},
  [112] = {.lex_state = 0},
  [113] = {.lex_state = 11},
  [114] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_SEMI] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_AMP] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_SQUOTE] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [aux_sym_hexdigit_token1] = ACTIONS(1),
    [aux_sym_hexdigit_token2] = ACTIONS(1),
    [sym_letter] = ACTIONS(1),
    [sym_digit] = ACTIONS(1),
    [sym_zerotoseven] = ACTIONS(1),
    [anon_sym_BSLASH] = ACTIONS(1),
    [anon_sym_v] = ACTIONS(1),
    [anon_sym_a] = ACTIONS(1),
    [anon_sym_b] = ACTIONS(1),
    [anon_sym_t] = ACTIONS(1),
    [anon_sym_n] = ACTIONS(1),
    [anon_sym_f] = ACTIONS(1),
    [anon_sym_r] = ACTIONS(1),
    [anon_sym_DOLLAR] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
    [anon_sym_BSLASHu] = ACTIONS(1),
  },
  [1] = {
    [sym_source_file] = STATE(114),
    [sym_statement] = STATE(8),
    [sym_localvarstatement] = STATE(55),
    [sym_assignmentormethodcall] = STATE(55),
    [sym_classorinterfacetype] = STATE(16),
    [sym_type] = STATE(35),
    [sym_typeliteral] = STATE(36),
    [sym_typeliteralexpr] = STATE(19),
    [sym_parenthexpr] = STATE(19),
    [sym_idclassorinterfacetype] = STATE(15),
    [sym_ident] = STATE(17),
    [sym_stringliteral] = STATE(19),
    [aux_sym_source_file_repeat1] = STATE(8),
    [ts_builtin_sym_end] = ACTIONS(3),
    [anon_sym_SEMI] = ACTIONS(5),
    [anon_sym_var] = ACTIONS(7),
    [anon_sym_LPAREN] = ACTIONS(9),
    [anon_sym_SQUOTE] = ACTIONS(11),
    [anon_sym_DQUOTE] = ACTIONS(13),
    [sym_letter] = ACTIONS(15),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 30,
    ACTIONS(11), 1,
      anon_sym_SQUOTE,
    ACTIONS(13), 1,
      anon_sym_DQUOTE,
    ACTIONS(17), 1,
      anon_sym_COLON,
    ACTIONS(19), 1,
      anon_sym_RPAREN,
    ACTIONS(21), 1,
      sym_letter,
    STATE(15), 1,
      sym_idclassorinterfacetype,
    STATE(16), 1,
      sym_classorinterfacetype,
    STATE(17), 1,
      sym_ident,
    STATE(23), 1,
      sym_equalityexpr,
    STATE(24), 1,
      sym_relationalexpr,
    STATE(25), 1,
      sym_intervalexpr,
    STATE(26), 1,
      sym_bitshiftexpr,
    STATE(27), 1,
      sym_additiveexpr,
    STATE(28), 1,
      sym_multiplicativeexpr,
    STATE(29), 1,
      sym_typeasexpr,
    STATE(30), 1,
      sym_unaryexpr,
    STATE(31), 1,
      sym_unaryexprnotplusminus,
    STATE(32), 1,
      sym_primaryexpr,
    STATE(33), 1,
      sym_stringliteral,
    STATE(36), 1,
      sym_typeliteral,
    STATE(37), 1,
      sym_conditionalexpr,
    STATE(38), 1,
      sym_conditionalorexpr,
    STATE(42), 1,
      sym_conditionalandexpr,
    STATE(43), 1,
      sym_bitwiseorexpr,
    STATE(44), 1,
      sym_bitwisexorexpr,
    STATE(45), 1,
      sym_bitwiseandexpr,
    STATE(96), 1,
      sym_argexpression,
    STATE(103), 1,
      sym_type,
    STATE(39), 2,
      sym_typeliteralexpr,
      sym_literal,
    STATE(107), 2,
      sym_expression,
      sym_namedargexpression,
  [93] = 29,
    ACTIONS(11), 1,
      anon_sym_SQUOTE,
    ACTIONS(13), 1,
      anon_sym_DQUOTE,
    ACTIONS(17), 1,
      anon_sym_COLON,
    ACTIONS(21), 1,
      sym_letter,
    STATE(15), 1,
      sym_idclassorinterfacetype,
    STATE(16), 1,
      sym_classorinterfacetype,
    STATE(17), 1,
      sym_ident,
    STATE(23), 1,
      sym_equalityexpr,
    STATE(24), 1,
      sym_relationalexpr,
    STATE(25), 1,
      sym_intervalexpr,
    STATE(26), 1,
      sym_bitshiftexpr,
    STATE(27), 1,
      sym_additiveexpr,
    STATE(28), 1,
      sym_multiplicativeexpr,
    STATE(29), 1,
      sym_typeasexpr,
    STATE(30), 1,
      sym_unaryexpr,
    STATE(31), 1,
      sym_unaryexprnotplusminus,
    STATE(32), 1,
      sym_primaryexpr,
    STATE(33), 1,
      sym_stringliteral,
    STATE(36), 1,
      sym_typeliteral,
    STATE(37), 1,
      sym_conditionalexpr,
    STATE(38), 1,
      sym_conditionalorexpr,
    STATE(42), 1,
      sym_conditionalandexpr,
    STATE(43), 1,
      sym_bitwiseorexpr,
    STATE(44), 1,
      sym_bitwisexorexpr,
    STATE(45), 1,
      sym_bitwiseandexpr,
    STATE(103), 1,
      sym_type,
    STATE(106), 1,
      sym_argexpression,
    STATE(39), 2,
      sym_typeliteralexpr,
      sym_literal,
    STATE(107), 2,
      sym_expression,
      sym_namedargexpression,
  [183] = 27,
    ACTIONS(11), 1,
      anon_sym_SQUOTE,
    ACTIONS(13), 1,
      anon_sym_DQUOTE,
    ACTIONS(21), 1,
      sym_letter,
    STATE(15), 1,
      sym_idclassorinterfacetype,
    STATE(16), 1,
      sym_classorinterfacetype,
    STATE(17), 1,
      sym_ident,
    STATE(23), 1,
      sym_equalityexpr,
    STATE(24), 1,
      sym_relationalexpr,
    STATE(25), 1,
      sym_intervalexpr,
    STATE(26), 1,
      sym_bitshiftexpr,
    STATE(27), 1,
      sym_additiveexpr,
    STATE(28), 1,
      sym_multiplicativeexpr,
    STATE(29), 1,
      sym_typeasexpr,
    STATE(30), 1,
      sym_unaryexpr,
    STATE(31), 1,
      sym_unaryexprnotplusminus,
    STATE(32), 1,
      sym_primaryexpr,
    STATE(33), 1,
      sym_stringliteral,
    STATE(36), 1,
      sym_typeliteral,
    STATE(37), 1,
      sym_conditionalexpr,
    STATE(38), 1,
      sym_conditionalorexpr,
    STATE(42), 1,
      sym_conditionalandexpr,
    STATE(43), 1,
      sym_bitwiseorexpr,
    STATE(44), 1,
      sym_bitwisexorexpr,
    STATE(45), 1,
      sym_bitwiseandexpr,
    STATE(103), 1,
      sym_type,
    STATE(112), 1,
      sym_expression,
    STATE(39), 2,
      sym_typeliteralexpr,
      sym_literal,
  [266] = 27,
    ACTIONS(11), 1,
      anon_sym_SQUOTE,
    ACTIONS(13), 1,
      anon_sym_DQUOTE,
    ACTIONS(23), 1,
      sym_letter,
    STATE(15), 1,
      sym_idclassorinterfacetype,
    STATE(16), 1,
      sym_classorinterfacetype,
    STATE(17), 1,
      sym_ident,
    STATE(23), 1,
      sym_equalityexpr,
    STATE(24), 1,
      sym_relationalexpr,
    STATE(25), 1,
      sym_intervalexpr,
    STATE(26), 1,
      sym_bitshiftexpr,
    STATE(27), 1,
      sym_additiveexpr,
    STATE(28), 1,
      sym_multiplicativeexpr,
    STATE(29), 1,
      sym_typeasexpr,
    STATE(30), 1,
      sym_unaryexpr,
    STATE(31), 1,
      sym_unaryexprnotplusminus,
    STATE(32), 1,
      sym_primaryexpr,
    STATE(33), 1,
      sym_stringliteral,
    STATE(35), 1,
      sym_type,
    STATE(36), 1,
      sym_typeliteral,
    STATE(37), 1,
      sym_conditionalexpr,
    STATE(38), 1,
      sym_conditionalorexpr,
    STATE(42), 1,
      sym_conditionalandexpr,
    STATE(43), 1,
      sym_bitwiseorexpr,
    STATE(44), 1,
      sym_bitwisexorexpr,
    STATE(45), 1,
      sym_bitwiseandexpr,
    STATE(59), 1,
      sym_expression,
    STATE(39), 2,
      sym_typeliteralexpr,
      sym_literal,
  [349] = 27,
    ACTIONS(11), 1,
      anon_sym_SQUOTE,
    ACTIONS(13), 1,
      anon_sym_DQUOTE,
    ACTIONS(23), 1,
      sym_letter,
    STATE(15), 1,
      sym_idclassorinterfacetype,
    STATE(16), 1,
      sym_classorinterfacetype,
    STATE(17), 1,
      sym_ident,
    STATE(23), 1,
      sym_equalityexpr,
    STATE(24), 1,
      sym_relationalexpr,
    STATE(25), 1,
      sym_intervalexpr,
    STATE(26), 1,
      sym_bitshiftexpr,
    STATE(27), 1,
      sym_additiveexpr,
    STATE(28), 1,
      sym_multiplicativeexpr,
    STATE(29), 1,
      sym_typeasexpr,
    STATE(30), 1,
      sym_unaryexpr,
    STATE(31), 1,
      sym_unaryexprnotplusminus,
    STATE(32), 1,
      sym_primaryexpr,
    STATE(33), 1,
      sym_stringliteral,
    STATE(35), 1,
      sym_type,
    STATE(36), 1,
      sym_typeliteral,
    STATE(37), 1,
      sym_conditionalexpr,
    STATE(38), 1,
      sym_conditionalorexpr,
    STATE(42), 1,
      sym_conditionalandexpr,
    STATE(43), 1,
      sym_bitwiseorexpr,
    STATE(44), 1,
      sym_bitwisexorexpr,
    STATE(45), 1,
      sym_bitwiseandexpr,
    STATE(61), 1,
      sym_expression,
    STATE(39), 2,
      sym_typeliteralexpr,
      sym_literal,
  [432] = 27,
    ACTIONS(11), 1,
      anon_sym_SQUOTE,
    ACTIONS(13), 1,
      anon_sym_DQUOTE,
    ACTIONS(21), 1,
      sym_letter,
    STATE(15), 1,
      sym_idclassorinterfacetype,
    STATE(16), 1,
      sym_classorinterfacetype,
    STATE(17), 1,
      sym_ident,
    STATE(23), 1,
      sym_equalityexpr,
    STATE(24), 1,
      sym_relationalexpr,
    STATE(25), 1,
      sym_intervalexpr,
    STATE(26), 1,
      sym_bitshiftexpr,
    STATE(27), 1,
      sym_additiveexpr,
    STATE(28), 1,
      sym_multiplicativeexpr,
    STATE(29), 1,
      sym_typeasexpr,
    STATE(30), 1,
      sym_unaryexpr,
    STATE(31), 1,
      sym_unaryexprnotplusminus,
    STATE(32), 1,
      sym_primaryexpr,
    STATE(33), 1,
      sym_stringliteral,
    STATE(36), 1,
      sym_typeliteral,
    STATE(37), 1,
      sym_conditionalexpr,
    STATE(38), 1,
      sym_conditionalorexpr,
    STATE(42), 1,
      sym_conditionalandexpr,
    STATE(43), 1,
      sym_bitwiseorexpr,
    STATE(44), 1,
      sym_bitwisexorexpr,
    STATE(45), 1,
      sym_bitwiseandexpr,
    STATE(103), 1,
      sym_type,
    STATE(105), 1,
      sym_expression,
    STATE(39), 2,
      sym_typeliteralexpr,
      sym_literal,
  [515] = 15,
    ACTIONS(5), 1,
      anon_sym_SEMI,
    ACTIONS(7), 1,
      anon_sym_var,
    ACTIONS(9), 1,
      anon_sym_LPAREN,
    ACTIONS(11), 1,
      anon_sym_SQUOTE,
    ACTIONS(13), 1,
      anon_sym_DQUOTE,
    ACTIONS(15), 1,
      sym_letter,
    ACTIONS(25), 1,
      ts_builtin_sym_end,
    STATE(15), 1,
      sym_idclassorinterfacetype,
    STATE(16), 1,
      sym_classorinterfacetype,
    STATE(17), 1,
      sym_ident,
    STATE(35), 1,
      sym_type,
    STATE(36), 1,
      sym_typeliteral,
    STATE(9), 2,
      sym_statement,
      aux_sym_source_file_repeat1,
    STATE(55), 2,
      sym_localvarstatement,
      sym_assignmentormethodcall,
    STATE(19), 3,
      sym_typeliteralexpr,
      sym_parenthexpr,
      sym_stringliteral,
  [565] = 15,
    ACTIONS(27), 1,
      ts_builtin_sym_end,
    ACTIONS(29), 1,
      anon_sym_SEMI,
    ACTIONS(32), 1,
      anon_sym_var,
    ACTIONS(35), 1,
      anon_sym_LPAREN,
    ACTIONS(38), 1,
      anon_sym_SQUOTE,
    ACTIONS(41), 1,
      anon_sym_DQUOTE,
    ACTIONS(44), 1,
      sym_letter,
    STATE(15), 1,
      sym_idclassorinterfacetype,
    STATE(16), 1,
      sym_classorinterfacetype,
    STATE(17), 1,
      sym_ident,
    STATE(35), 1,
      sym_type,
    STATE(36), 1,
      sym_typeliteral,
    STATE(9), 2,
      sym_statement,
      aux_sym_source_file_repeat1,
    STATE(55), 2,
      sym_localvarstatement,
      sym_assignmentormethodcall,
    STATE(19), 3,
      sym_typeliteralexpr,
      sym_parenthexpr,
      sym_stringliteral,
  [615] = 3,
    ACTIONS(49), 1,
      sym_zerotoseven,
    ACTIONS(51), 1,
      aux_sym_octalescape_token1,
    ACTIONS(47), 12,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      anon_sym_BSLASH,
      anon_sym_v,
      anon_sym_a,
      anon_sym_b,
      anon_sym_t,
      anon_sym_n,
      anon_sym_f,
      anon_sym_r,
      anon_sym_DOLLAR,
      anon_sym_LT,
  [636] = 3,
    ACTIONS(55), 1,
      sym_zerotoseven,
    ACTIONS(57), 1,
      aux_sym_octalescape_token1,
    ACTIONS(53), 12,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      anon_sym_BSLASH,
      anon_sym_v,
      anon_sym_a,
      anon_sym_b,
      anon_sym_t,
      anon_sym_n,
      anon_sym_f,
      anon_sym_r,
      anon_sym_DOLLAR,
      anon_sym_LT,
  [657] = 4,
    ACTIONS(61), 1,
      sym_letter,
    ACTIONS(63), 1,
      sym_digit,
    STATE(14), 1,
      aux_sym_ident_repeat1,
    ACTIONS(59), 9,
      ts_builtin_sym_end,
      anon_sym_COLON,
      anon_sym_SEMI,
      anon_sym_var,
      anon_sym_EQ,
      anon_sym_AMP,
      anon_sym_LPAREN,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
  [678] = 4,
    ACTIONS(67), 1,
      sym_letter,
    ACTIONS(69), 1,
      sym_digit,
    STATE(12), 1,
      aux_sym_ident_repeat1,
    ACTIONS(65), 9,
      ts_builtin_sym_end,
      anon_sym_COLON,
      anon_sym_SEMI,
      anon_sym_var,
      anon_sym_EQ,
      anon_sym_AMP,
      anon_sym_LPAREN,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
  [699] = 4,
    ACTIONS(73), 1,
      sym_letter,
    ACTIONS(76), 1,
      sym_digit,
    STATE(14), 1,
      aux_sym_ident_repeat1,
    ACTIONS(71), 9,
      ts_builtin_sym_end,
      anon_sym_COLON,
      anon_sym_SEMI,
      anon_sym_var,
      anon_sym_EQ,
      anon_sym_AMP,
      anon_sym_LPAREN,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
  [720] = 2,
    ACTIONS(81), 1,
      sym_letter,
    ACTIONS(79), 10,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_var,
      anon_sym_EQ,
      anon_sym_AMP,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
  [736] = 2,
    ACTIONS(85), 1,
      sym_letter,
    ACTIONS(83), 10,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_var,
      anon_sym_EQ,
      anon_sym_AMP,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
  [752] = 2,
    ACTIONS(89), 1,
      sym_letter,
    ACTIONS(87), 10,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_var,
      anon_sym_EQ,
      anon_sym_AMP,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
  [768] = 5,
    ACTIONS(93), 1,
      anon_sym_LPAREN,
    ACTIONS(95), 1,
      sym_letter,
    STATE(58), 1,
      sym_arguments,
    STATE(20), 2,
      sym_indirectmemberaccessone,
      aux_sym_assignmentormethodcall_repeat1,
    ACTIONS(91), 5,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_var,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
  [789] = 5,
    ACTIONS(93), 1,
      anon_sym_LPAREN,
    ACTIONS(99), 1,
      sym_letter,
    STATE(58), 1,
      sym_arguments,
    STATE(18), 2,
      sym_indirectmemberaccessone,
      aux_sym_assignmentormethodcall_repeat1,
    ACTIONS(97), 5,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_var,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
  [810] = 5,
    ACTIONS(103), 1,
      anon_sym_LPAREN,
    ACTIONS(106), 1,
      sym_letter,
    STATE(58), 1,
      sym_arguments,
    STATE(20), 2,
      sym_indirectmemberaccessone,
      aux_sym_assignmentormethodcall_repeat1,
    ACTIONS(101), 5,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_var,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
  [831] = 5,
    ACTIONS(110), 1,
      anon_sym_COLON,
    ACTIONS(112), 1,
      anon_sym_EQ,
    ACTIONS(114), 1,
      sym_letter,
    STATE(53), 1,
      sym_typeannotation,
    ACTIONS(108), 6,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_var,
      anon_sym_LPAREN,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
  [852] = 2,
    ACTIONS(118), 1,
      sym_letter,
    ACTIONS(116), 9,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_var,
      anon_sym_EQ,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
  [867] = 2,
    ACTIONS(122), 1,
      sym_letter,
    ACTIONS(120), 8,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_var,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
  [881] = 2,
    ACTIONS(126), 1,
      sym_letter,
    ACTIONS(124), 8,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_var,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
  [895] = 2,
    ACTIONS(130), 1,
      sym_letter,
    ACTIONS(128), 8,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_var,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
  [909] = 2,
    ACTIONS(134), 1,
      sym_letter,
    ACTIONS(132), 8,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_var,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
  [923] = 2,
    ACTIONS(138), 1,
      sym_letter,
    ACTIONS(136), 8,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_var,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
  [937] = 2,
    ACTIONS(142), 1,
      sym_letter,
    ACTIONS(140), 8,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_var,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
  [951] = 2,
    ACTIONS(146), 1,
      sym_letter,
    ACTIONS(144), 8,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_var,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
  [965] = 2,
    ACTIONS(150), 1,
      sym_letter,
    ACTIONS(148), 8,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_var,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
  [979] = 2,
    ACTIONS(154), 1,
      sym_letter,
    ACTIONS(152), 8,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_var,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
  [993] = 2,
    ACTIONS(158), 1,
      sym_letter,
    ACTIONS(156), 8,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_var,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
  [1007] = 2,
    ACTIONS(162), 1,
      sym_letter,
    ACTIONS(160), 8,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_var,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
  [1021] = 2,
    ACTIONS(166), 1,
      sym_letter,
    ACTIONS(164), 8,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_var,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
  [1035] = 3,
    ACTIONS(170), 1,
      anon_sym_AMP,
    ACTIONS(172), 1,
      sym_letter,
    ACTIONS(168), 7,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_var,
      anon_sym_EQ,
      anon_sym_LPAREN,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
  [1051] = 2,
    ACTIONS(176), 1,
      sym_letter,
    ACTIONS(174), 8,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_var,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
  [1065] = 2,
    ACTIONS(180), 1,
      sym_letter,
    ACTIONS(178), 8,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_var,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
  [1079] = 2,
    ACTIONS(184), 1,
      sym_letter,
    ACTIONS(182), 8,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_var,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
  [1093] = 2,
    ACTIONS(188), 1,
      sym_letter,
    ACTIONS(186), 8,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_var,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
  [1107] = 2,
    ACTIONS(192), 1,
      sym_letter,
    ACTIONS(190), 8,
      ts_builtin_sym_end,
      anon_sym_COLON,
      anon_sym_SEMI,
      anon_sym_var,
      anon_sym_EQ,
      anon_sym_LPAREN,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
  [1121] = 2,
    ACTIONS(196), 1,
      sym_letter,
    ACTIONS(194), 8,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_var,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
  [1135] = 2,
    ACTIONS(200), 1,
      sym_letter,
    ACTIONS(198), 8,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_var,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
  [1149] = 2,
    ACTIONS(204), 1,
      sym_letter,
    ACTIONS(202), 8,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_var,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
  [1163] = 2,
    ACTIONS(208), 1,
      sym_letter,
    ACTIONS(206), 8,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_var,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
  [1177] = 2,
    ACTIONS(212), 1,
      sym_letter,
    ACTIONS(210), 8,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_var,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
  [1191] = 6,
    ACTIONS(214), 1,
      anon_sym_SQUOTE,
    ACTIONS(216), 1,
      anon_sym_BSLASH,
    ACTIONS(218), 1,
      anon_sym_BSLASHu,
    ACTIONS(220), 1,
      sym_any_character,
    STATE(47), 2,
      sym_escapesequence,
      aux_sym_stringliteral_repeat1,
    STATE(80), 2,
      sym_octalescape,
      sym_unicodeescape,
  [1212] = 6,
    ACTIONS(222), 1,
      anon_sym_SQUOTE,
    ACTIONS(224), 1,
      anon_sym_BSLASH,
    ACTIONS(227), 1,
      anon_sym_BSLASHu,
    ACTIONS(230), 1,
      sym_any_character,
    STATE(47), 2,
      sym_escapesequence,
      aux_sym_stringliteral_repeat1,
    STATE(80), 2,
      sym_octalescape,
      sym_unicodeescape,
  [1233] = 6,
    ACTIONS(214), 1,
      anon_sym_DQUOTE,
    ACTIONS(233), 1,
      anon_sym_BSLASH,
    ACTIONS(235), 1,
      anon_sym_BSLASHu,
    ACTIONS(237), 1,
      sym_any_character,
    STATE(52), 2,
      sym_escapesequence,
      aux_sym_stringliteral_repeat1,
    STATE(79), 2,
      sym_octalescape,
      sym_unicodeescape,
  [1254] = 6,
    ACTIONS(216), 1,
      anon_sym_BSLASH,
    ACTIONS(218), 1,
      anon_sym_BSLASHu,
    ACTIONS(239), 1,
      anon_sym_SQUOTE,
    ACTIONS(241), 1,
      sym_any_character,
    STATE(46), 2,
      sym_escapesequence,
      aux_sym_stringliteral_repeat1,
    STATE(80), 2,
      sym_octalescape,
      sym_unicodeescape,
  [1275] = 2,
    ACTIONS(245), 1,
      sym_letter,
    ACTIONS(243), 7,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_var,
      anon_sym_EQ,
      anon_sym_LPAREN,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
  [1288] = 6,
    ACTIONS(233), 1,
      anon_sym_BSLASH,
    ACTIONS(235), 1,
      anon_sym_BSLASHu,
    ACTIONS(239), 1,
      anon_sym_DQUOTE,
    ACTIONS(247), 1,
      sym_any_character,
    STATE(48), 2,
      sym_escapesequence,
      aux_sym_stringliteral_repeat1,
    STATE(79), 2,
      sym_octalescape,
      sym_unicodeescape,
  [1309] = 6,
    ACTIONS(222), 1,
      anon_sym_DQUOTE,
    ACTIONS(249), 1,
      anon_sym_BSLASH,
    ACTIONS(252), 1,
      anon_sym_BSLASHu,
    ACTIONS(255), 1,
      sym_any_character,
    STATE(52), 2,
      sym_escapesequence,
      aux_sym_stringliteral_repeat1,
    STATE(79), 2,
      sym_octalescape,
      sym_unicodeescape,
  [1330] = 3,
    ACTIONS(260), 1,
      anon_sym_EQ,
    ACTIONS(262), 1,
      sym_letter,
    ACTIONS(258), 6,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_var,
      anon_sym_LPAREN,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
  [1345] = 2,
    ACTIONS(266), 1,
      sym_letter,
    ACTIONS(264), 6,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_var,
      anon_sym_LPAREN,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
  [1357] = 3,
    ACTIONS(266), 1,
      sym_letter,
    ACTIONS(268), 1,
      anon_sym_SEMI,
    ACTIONS(264), 5,
      ts_builtin_sym_end,
      anon_sym_var,
      anon_sym_LPAREN,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
  [1371] = 2,
    ACTIONS(272), 1,
      sym_letter,
    ACTIONS(270), 6,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_var,
      anon_sym_LPAREN,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
  [1383] = 2,
    ACTIONS(276), 1,
      sym_letter,
    ACTIONS(274), 6,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_var,
      anon_sym_LPAREN,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
  [1395] = 2,
    ACTIONS(280), 1,
      sym_letter,
    ACTIONS(278), 6,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_var,
      anon_sym_LPAREN,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
  [1407] = 2,
    ACTIONS(284), 1,
      sym_letter,
    ACTIONS(282), 6,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_var,
      anon_sym_LPAREN,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
  [1419] = 2,
    ACTIONS(288), 1,
      sym_letter,
    ACTIONS(286), 6,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_var,
      anon_sym_LPAREN,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
  [1431] = 2,
    ACTIONS(292), 1,
      sym_letter,
    ACTIONS(290), 6,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_var,
      anon_sym_LPAREN,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
  [1443] = 2,
    ACTIONS(296), 1,
      sym_letter,
    ACTIONS(294), 6,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_var,
      anon_sym_LPAREN,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
  [1455] = 3,
    STATE(64), 1,
      aux_sym_ident_repeat1,
    ACTIONS(298), 2,
      sym_letter,
      sym_digit,
    ACTIONS(65), 4,
      anon_sym_EQ,
      anon_sym_AMP,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [1469] = 3,
    STATE(65), 1,
      aux_sym_ident_repeat1,
    ACTIONS(300), 2,
      sym_letter,
      sym_digit,
    ACTIONS(59), 4,
      anon_sym_EQ,
      anon_sym_AMP,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [1483] = 3,
    STATE(65), 1,
      aux_sym_ident_repeat1,
    ACTIONS(302), 2,
      sym_letter,
      sym_digit,
    ACTIONS(71), 4,
      anon_sym_EQ,
      anon_sym_AMP,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [1497] = 2,
    ACTIONS(307), 1,
      sym_letter,
    ACTIONS(305), 6,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_var,
      anon_sym_LPAREN,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
  [1509] = 6,
    ACTIONS(23), 1,
      sym_letter,
    STATE(15), 1,
      sym_idclassorinterfacetype,
    STATE(16), 1,
      sym_classorinterfacetype,
    STATE(17), 1,
      sym_ident,
    STATE(35), 1,
      sym_type,
    STATE(50), 1,
      sym_typeliteral,
  [1528] = 2,
    ACTIONS(311), 1,
      sym_zerotoseven,
    ACTIONS(309), 4,
      anon_sym_SQUOTE,
      anon_sym_BSLASH,
      anon_sym_BSLASHu,
      sym_any_character,
  [1538] = 5,
    ACTIONS(21), 1,
      sym_letter,
    STATE(15), 1,
      sym_idclassorinterfacetype,
    STATE(16), 1,
      sym_classorinterfacetype,
    STATE(17), 1,
      sym_ident,
    STATE(22), 1,
      sym_type,
  [1554] = 5,
    ACTIONS(23), 1,
      sym_letter,
    STATE(15), 1,
      sym_idclassorinterfacetype,
    STATE(16), 1,
      sym_classorinterfacetype,
    STATE(17), 1,
      sym_ident,
    STATE(22), 1,
      sym_type,
  [1570] = 2,
    ACTIONS(313), 1,
      sym_zerotoseven,
    ACTIONS(309), 4,
      anon_sym_DQUOTE,
      anon_sym_BSLASH,
      anon_sym_BSLASHu,
      sym_any_character,
  [1580] = 4,
    ACTIONS(315), 1,
      aux_sym_hexdigit_token1,
    ACTIONS(317), 1,
      aux_sym_hexdigit_token2,
    ACTIONS(319), 1,
      sym_digit,
    STATE(81), 1,
      sym_hexdigit,
  [1593] = 4,
    ACTIONS(315), 1,
      aux_sym_hexdigit_token1,
    ACTIONS(317), 1,
      aux_sym_hexdigit_token2,
    ACTIONS(319), 1,
      sym_digit,
    STATE(72), 1,
      sym_hexdigit,
  [1606] = 1,
    ACTIONS(321), 4,
      anon_sym_SQUOTE,
      anon_sym_BSLASH,
      anon_sym_BSLASHu,
      sym_any_character,
  [1613] = 1,
    ACTIONS(323), 4,
      anon_sym_SQUOTE,
      anon_sym_BSLASH,
      anon_sym_BSLASHu,
      sym_any_character,
  [1620] = 1,
    ACTIONS(325), 4,
      anon_sym_SQUOTE,
      anon_sym_BSLASH,
      anon_sym_BSLASHu,
      sym_any_character,
  [1627] = 1,
    ACTIONS(327), 4,
      anon_sym_SQUOTE,
      anon_sym_BSLASH,
      anon_sym_BSLASHu,
      sym_any_character,
  [1634] = 4,
    ACTIONS(315), 1,
      aux_sym_hexdigit_token1,
    ACTIONS(317), 1,
      aux_sym_hexdigit_token2,
    ACTIONS(319), 1,
      sym_digit,
    STATE(73), 1,
      sym_hexdigit,
  [1647] = 1,
    ACTIONS(329), 4,
      anon_sym_DQUOTE,
      anon_sym_BSLASH,
      anon_sym_BSLASHu,
      sym_any_character,
  [1654] = 1,
    ACTIONS(329), 4,
      anon_sym_SQUOTE,
      anon_sym_BSLASH,
      anon_sym_BSLASHu,
      sym_any_character,
  [1661] = 4,
    ACTIONS(331), 1,
      aux_sym_hexdigit_token1,
    ACTIONS(333), 1,
      aux_sym_hexdigit_token2,
    ACTIONS(335), 1,
      sym_digit,
    STATE(77), 1,
      sym_hexdigit,
  [1674] = 1,
    ACTIONS(323), 4,
      anon_sym_DQUOTE,
      anon_sym_BSLASH,
      anon_sym_BSLASHu,
      sym_any_character,
  [1681] = 1,
    ACTIONS(337), 4,
      anon_sym_SQUOTE,
      anon_sym_BSLASH,
      anon_sym_BSLASHu,
      sym_any_character,
  [1688] = 1,
    ACTIONS(339), 4,
      anon_sym_SQUOTE,
      anon_sym_BSLASH,
      anon_sym_BSLASHu,
      sym_any_character,
  [1695] = 1,
    ACTIONS(341), 4,
      anon_sym_SQUOTE,
      anon_sym_BSLASH,
      anon_sym_BSLASHu,
      sym_any_character,
  [1702] = 1,
    ACTIONS(325), 4,
      anon_sym_DQUOTE,
      anon_sym_BSLASH,
      anon_sym_BSLASHu,
      sym_any_character,
  [1709] = 1,
    ACTIONS(321), 4,
      anon_sym_DQUOTE,
      anon_sym_BSLASH,
      anon_sym_BSLASHu,
      sym_any_character,
  [1716] = 1,
    ACTIONS(327), 4,
      anon_sym_DQUOTE,
      anon_sym_BSLASH,
      anon_sym_BSLASHu,
      sym_any_character,
  [1723] = 1,
    ACTIONS(337), 4,
      anon_sym_DQUOTE,
      anon_sym_BSLASH,
      anon_sym_BSLASHu,
      sym_any_character,
  [1730] = 1,
    ACTIONS(339), 4,
      anon_sym_DQUOTE,
      anon_sym_BSLASH,
      anon_sym_BSLASHu,
      sym_any_character,
  [1737] = 1,
    ACTIONS(341), 4,
      anon_sym_DQUOTE,
      anon_sym_BSLASH,
      anon_sym_BSLASHu,
      sym_any_character,
  [1744] = 4,
    ACTIONS(343), 1,
      aux_sym_hexdigit_token1,
    ACTIONS(345), 1,
      aux_sym_hexdigit_token2,
    ACTIONS(347), 1,
      sym_digit,
    STATE(88), 1,
      sym_hexdigit,
  [1757] = 4,
    ACTIONS(315), 1,
      aux_sym_hexdigit_token1,
    ACTIONS(317), 1,
      aux_sym_hexdigit_token2,
    ACTIONS(319), 1,
      sym_digit,
    STATE(92), 1,
      sym_hexdigit,
  [1770] = 4,
    ACTIONS(315), 1,
      aux_sym_hexdigit_token1,
    ACTIONS(317), 1,
      aux_sym_hexdigit_token2,
    ACTIONS(319), 1,
      sym_digit,
    STATE(93), 1,
      sym_hexdigit,
  [1783] = 4,
    ACTIONS(315), 1,
      aux_sym_hexdigit_token1,
    ACTIONS(317), 1,
      aux_sym_hexdigit_token2,
    ACTIONS(319), 1,
      sym_digit,
    STATE(94), 1,
      sym_hexdigit,
  [1796] = 3,
    ACTIONS(349), 1,
      anon_sym_RPAREN,
    ACTIONS(351), 1,
      anon_sym_COMMA,
    STATE(102), 1,
      aux_sym_arguments_repeat1,
  [1806] = 3,
    ACTIONS(23), 1,
      sym_letter,
    STATE(21), 1,
      sym_id,
    STATE(40), 1,
      sym_ident,
  [1816] = 1,
    ACTIONS(353), 3,
      aux_sym_hexdigit_token1,
      aux_sym_hexdigit_token2,
      sym_digit,
  [1822] = 3,
    ACTIONS(21), 1,
      sym_letter,
    STATE(40), 1,
      sym_ident,
    STATE(108), 1,
      sym_id,
  [1832] = 1,
    ACTIONS(355), 3,
      aux_sym_hexdigit_token1,
      aux_sym_hexdigit_token2,
      sym_digit,
  [1838] = 3,
    ACTIONS(357), 1,
      anon_sym_RPAREN,
    ACTIONS(359), 1,
      anon_sym_COMMA,
    STATE(101), 1,
      aux_sym_arguments_repeat1,
  [1848] = 3,
    ACTIONS(351), 1,
      anon_sym_COMMA,
    ACTIONS(362), 1,
      anon_sym_RPAREN,
    STATE(101), 1,
      aux_sym_arguments_repeat1,
  [1858] = 2,
    ACTIONS(364), 1,
      anon_sym_AMP,
    ACTIONS(168), 2,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [1866] = 1,
    ACTIONS(366), 3,
      aux_sym_hexdigit_token1,
      aux_sym_hexdigit_token2,
      sym_digit,
  [1872] = 1,
    ACTIONS(368), 2,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [1877] = 1,
    ACTIONS(357), 2,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [1882] = 1,
    ACTIONS(370), 2,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [1887] = 1,
    ACTIONS(372), 1,
      anon_sym_EQ,
  [1891] = 1,
    ACTIONS(374), 1,
      sym_zerotoseven,
  [1895] = 1,
    ACTIONS(376), 1,
      sym_zerotoseven,
  [1899] = 1,
    ACTIONS(378), 1,
      sym_zerotoseven,
  [1903] = 1,
    ACTIONS(380), 1,
      anon_sym_RPAREN,
  [1907] = 1,
    ACTIONS(382), 1,
      sym_zerotoseven,
  [1911] = 1,
    ACTIONS(384), 1,
      ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 93,
  [SMALL_STATE(4)] = 183,
  [SMALL_STATE(5)] = 266,
  [SMALL_STATE(6)] = 349,
  [SMALL_STATE(7)] = 432,
  [SMALL_STATE(8)] = 515,
  [SMALL_STATE(9)] = 565,
  [SMALL_STATE(10)] = 615,
  [SMALL_STATE(11)] = 636,
  [SMALL_STATE(12)] = 657,
  [SMALL_STATE(13)] = 678,
  [SMALL_STATE(14)] = 699,
  [SMALL_STATE(15)] = 720,
  [SMALL_STATE(16)] = 736,
  [SMALL_STATE(17)] = 752,
  [SMALL_STATE(18)] = 768,
  [SMALL_STATE(19)] = 789,
  [SMALL_STATE(20)] = 810,
  [SMALL_STATE(21)] = 831,
  [SMALL_STATE(22)] = 852,
  [SMALL_STATE(23)] = 867,
  [SMALL_STATE(24)] = 881,
  [SMALL_STATE(25)] = 895,
  [SMALL_STATE(26)] = 909,
  [SMALL_STATE(27)] = 923,
  [SMALL_STATE(28)] = 937,
  [SMALL_STATE(29)] = 951,
  [SMALL_STATE(30)] = 965,
  [SMALL_STATE(31)] = 979,
  [SMALL_STATE(32)] = 993,
  [SMALL_STATE(33)] = 1007,
  [SMALL_STATE(34)] = 1021,
  [SMALL_STATE(35)] = 1035,
  [SMALL_STATE(36)] = 1051,
  [SMALL_STATE(37)] = 1065,
  [SMALL_STATE(38)] = 1079,
  [SMALL_STATE(39)] = 1093,
  [SMALL_STATE(40)] = 1107,
  [SMALL_STATE(41)] = 1121,
  [SMALL_STATE(42)] = 1135,
  [SMALL_STATE(43)] = 1149,
  [SMALL_STATE(44)] = 1163,
  [SMALL_STATE(45)] = 1177,
  [SMALL_STATE(46)] = 1191,
  [SMALL_STATE(47)] = 1212,
  [SMALL_STATE(48)] = 1233,
  [SMALL_STATE(49)] = 1254,
  [SMALL_STATE(50)] = 1275,
  [SMALL_STATE(51)] = 1288,
  [SMALL_STATE(52)] = 1309,
  [SMALL_STATE(53)] = 1330,
  [SMALL_STATE(54)] = 1345,
  [SMALL_STATE(55)] = 1357,
  [SMALL_STATE(56)] = 1371,
  [SMALL_STATE(57)] = 1383,
  [SMALL_STATE(58)] = 1395,
  [SMALL_STATE(59)] = 1407,
  [SMALL_STATE(60)] = 1419,
  [SMALL_STATE(61)] = 1431,
  [SMALL_STATE(62)] = 1443,
  [SMALL_STATE(63)] = 1455,
  [SMALL_STATE(64)] = 1469,
  [SMALL_STATE(65)] = 1483,
  [SMALL_STATE(66)] = 1497,
  [SMALL_STATE(67)] = 1509,
  [SMALL_STATE(68)] = 1528,
  [SMALL_STATE(69)] = 1538,
  [SMALL_STATE(70)] = 1554,
  [SMALL_STATE(71)] = 1570,
  [SMALL_STATE(72)] = 1580,
  [SMALL_STATE(73)] = 1593,
  [SMALL_STATE(74)] = 1606,
  [SMALL_STATE(75)] = 1613,
  [SMALL_STATE(76)] = 1620,
  [SMALL_STATE(77)] = 1627,
  [SMALL_STATE(78)] = 1634,
  [SMALL_STATE(79)] = 1647,
  [SMALL_STATE(80)] = 1654,
  [SMALL_STATE(81)] = 1661,
  [SMALL_STATE(82)] = 1674,
  [SMALL_STATE(83)] = 1681,
  [SMALL_STATE(84)] = 1688,
  [SMALL_STATE(85)] = 1695,
  [SMALL_STATE(86)] = 1702,
  [SMALL_STATE(87)] = 1709,
  [SMALL_STATE(88)] = 1716,
  [SMALL_STATE(89)] = 1723,
  [SMALL_STATE(90)] = 1730,
  [SMALL_STATE(91)] = 1737,
  [SMALL_STATE(92)] = 1744,
  [SMALL_STATE(93)] = 1757,
  [SMALL_STATE(94)] = 1770,
  [SMALL_STATE(95)] = 1783,
  [SMALL_STATE(96)] = 1796,
  [SMALL_STATE(97)] = 1806,
  [SMALL_STATE(98)] = 1816,
  [SMALL_STATE(99)] = 1822,
  [SMALL_STATE(100)] = 1832,
  [SMALL_STATE(101)] = 1838,
  [SMALL_STATE(102)] = 1848,
  [SMALL_STATE(103)] = 1858,
  [SMALL_STATE(104)] = 1866,
  [SMALL_STATE(105)] = 1872,
  [SMALL_STATE(106)] = 1877,
  [SMALL_STATE(107)] = 1882,
  [SMALL_STATE(108)] = 1887,
  [SMALL_STATE(109)] = 1891,
  [SMALL_STATE(110)] = 1895,
  [SMALL_STATE(111)] = 1899,
  [SMALL_STATE(112)] = 1903,
  [SMALL_STATE(113)] = 1907,
  [SMALL_STATE(114)] = 1911,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(97),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(13),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(99),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [25] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [27] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [29] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(54),
  [32] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(97),
  [35] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(4),
  [38] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(49),
  [41] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(51),
  [44] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(13),
  [47] = {.entry = {.count = 1, .reusable = true}}, SHIFT(75),
  [49] = {.entry = {.count = 1, .reusable = false}}, SHIFT(68),
  [51] = {.entry = {.count = 1, .reusable = true}}, SHIFT(109),
  [53] = {.entry = {.count = 1, .reusable = true}}, SHIFT(82),
  [55] = {.entry = {.count = 1, .reusable = false}}, SHIFT(71),
  [57] = {.entry = {.count = 1, .reusable = true}}, SHIFT(111),
  [59] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_ident, 2, 0, 0),
  [61] = {.entry = {.count = 1, .reusable = false}}, SHIFT(14),
  [63] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [65] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_ident, 1, 0, 0),
  [67] = {.entry = {.count = 1, .reusable = false}}, SHIFT(12),
  [69] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [71] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_ident_repeat1, 2, 0, 0),
  [73] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_ident_repeat1, 2, 0, 0), SHIFT_REPEAT(14),
  [76] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_ident_repeat1, 2, 0, 0), SHIFT_REPEAT(14),
  [79] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_classorinterfacetype, 1, 0, 0),
  [81] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_classorinterfacetype, 1, 0, 0),
  [83] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type, 1, 0, 0),
  [85] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_type, 1, 0, 0),
  [87] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_idclassorinterfacetype, 1, 0, 0),
  [89] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_idclassorinterfacetype, 1, 0, 0),
  [91] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_assignmentormethodcall, 2, 0, 0),
  [93] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [95] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_assignmentormethodcall, 2, 0, 0),
  [97] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_assignmentormethodcall, 1, 0, 0),
  [99] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_assignmentormethodcall, 1, 0, 0),
  [101] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_assignmentormethodcall_repeat1, 2, 0, 0),
  [103] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_assignmentormethodcall_repeat1, 2, 0, 0), SHIFT_REPEAT(2),
  [106] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_assignmentormethodcall_repeat1, 2, 0, 0),
  [108] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_localvarstatement, 2, 0, 0),
  [110] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [112] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [114] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_localvarstatement, 2, 0, 0),
  [116] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_typeliteral, 3, 0, 0),
  [118] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_typeliteral, 3, 0, 0),
  [120] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_bitwiseandexpr, 1, 0, 0),
  [122] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_bitwiseandexpr, 1, 0, 0),
  [124] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_equalityexpr, 1, 0, 0),
  [126] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_equalityexpr, 1, 0, 0),
  [128] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_relationalexpr, 1, 0, 0),
  [130] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_relationalexpr, 1, 0, 0),
  [132] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_intervalexpr, 1, 0, 0),
  [134] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_intervalexpr, 1, 0, 0),
  [136] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_bitshiftexpr, 1, 0, 0),
  [138] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_bitshiftexpr, 1, 0, 0),
  [140] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_additiveexpr, 1, 0, 0),
  [142] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_additiveexpr, 1, 0, 0),
  [144] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_multiplicativeexpr, 1, 0, 0),
  [146] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_multiplicativeexpr, 1, 0, 0),
  [148] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_typeasexpr, 1, 0, 0),
  [150] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_typeasexpr, 1, 0, 0),
  [152] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_unaryexpr, 1, 0, 0),
  [154] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_unaryexpr, 1, 0, 0),
  [156] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_unaryexprnotplusminus, 1, 0, 0),
  [158] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_unaryexprnotplusminus, 1, 0, 0),
  [160] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_literal, 1, 0, 0),
  [162] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_literal, 1, 0, 0),
  [164] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_stringliteral, 2, 0, 0),
  [166] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_stringliteral, 2, 0, 0),
  [168] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_typeliteral, 1, 0, 0),
  [170] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [172] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_typeliteral, 1, 0, 0),
  [174] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_typeliteralexpr, 1, 0, 0),
  [176] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_typeliteralexpr, 1, 0, 0),
  [178] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression, 1, 0, 0),
  [180] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_expression, 1, 0, 0),
  [182] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_conditionalexpr, 1, 0, 0),
  [184] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_conditionalexpr, 1, 0, 0),
  [186] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_primaryexpr, 1, 0, 0),
  [188] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_primaryexpr, 1, 0, 0),
  [190] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_id, 1, 0, 0),
  [192] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_id, 1, 0, 0),
  [194] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_stringliteral, 3, 0, 0),
  [196] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_stringliteral, 3, 0, 0),
  [198] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_conditionalorexpr, 1, 0, 0),
  [200] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_conditionalorexpr, 1, 0, 0),
  [202] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_conditionalandexpr, 1, 0, 0),
  [204] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_conditionalandexpr, 1, 0, 0),
  [206] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_bitwiseorexpr, 1, 0, 0),
  [208] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_bitwiseorexpr, 1, 0, 0),
  [210] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_bitwisexorexpr, 1, 0, 0),
  [212] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_bitwisexorexpr, 1, 0, 0),
  [214] = {.entry = {.count = 1, .reusable = false}}, SHIFT(41),
  [216] = {.entry = {.count = 1, .reusable = false}}, SHIFT(10),
  [218] = {.entry = {.count = 1, .reusable = false}}, SHIFT(78),
  [220] = {.entry = {.count = 1, .reusable = false}}, SHIFT(47),
  [222] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_stringliteral_repeat1, 2, 0, 0),
  [224] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_stringliteral_repeat1, 2, 0, 0), SHIFT_REPEAT(10),
  [227] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_stringliteral_repeat1, 2, 0, 0), SHIFT_REPEAT(78),
  [230] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_stringliteral_repeat1, 2, 0, 0), SHIFT_REPEAT(47),
  [233] = {.entry = {.count = 1, .reusable = false}}, SHIFT(11),
  [235] = {.entry = {.count = 1, .reusable = false}}, SHIFT(95),
  [237] = {.entry = {.count = 1, .reusable = false}}, SHIFT(52),
  [239] = {.entry = {.count = 1, .reusable = false}}, SHIFT(34),
  [241] = {.entry = {.count = 1, .reusable = false}}, SHIFT(46),
  [243] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_typeannotation, 2, 0, 0),
  [245] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_typeannotation, 2, 0, 0),
  [247] = {.entry = {.count = 1, .reusable = false}}, SHIFT(48),
  [249] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_stringliteral_repeat1, 2, 0, 0), SHIFT_REPEAT(11),
  [252] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_stringliteral_repeat1, 2, 0, 0), SHIFT_REPEAT(95),
  [255] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_stringliteral_repeat1, 2, 0, 0), SHIFT_REPEAT(52),
  [258] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_localvarstatement, 3, 0, 0),
  [260] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [262] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_localvarstatement, 3, 0, 0),
  [264] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_statement, 1, 0, 0),
  [266] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_statement, 1, 0, 0),
  [268] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [270] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_arguments, 2, 0, 0),
  [272] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_arguments, 2, 0, 0),
  [274] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_statement, 2, 0, 0),
  [276] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_statement, 2, 0, 0),
  [278] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_indirectmemberaccessone, 1, 0, 0),
  [280] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_indirectmemberaccessone, 1, 0, 0),
  [282] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_localvarstatement, 4, 0, 0),
  [284] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_localvarstatement, 4, 0, 0),
  [286] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_arguments, 3, 0, 0),
  [288] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_arguments, 3, 0, 0),
  [290] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_localvarstatement, 5, 0, 0),
  [292] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_localvarstatement, 5, 0, 0),
  [294] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_arguments, 4, 0, 0),
  [296] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_arguments, 4, 0, 0),
  [298] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [300] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [302] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_ident_repeat1, 2, 0, 0), SHIFT_REPEAT(65),
  [305] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parenthexpr, 3, 0, 0),
  [307] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_parenthexpr, 3, 0, 0),
  [309] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_octalescape, 2, 0, 0),
  [311] = {.entry = {.count = 1, .reusable = false}}, SHIFT(76),
  [313] = {.entry = {.count = 1, .reusable = false}}, SHIFT(86),
  [315] = {.entry = {.count = 1, .reusable = true}}, SHIFT(104),
  [317] = {.entry = {.count = 1, .reusable = true}}, SHIFT(98),
  [319] = {.entry = {.count = 1, .reusable = true}}, SHIFT(100),
  [321] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_octalescape, 4, 0, 3),
  [323] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_escapesequence, 2, 0, 0),
  [325] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_octalescape, 3, 0, 0),
  [327] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_unicodeescape, 5, 0, 0),
  [329] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_escapesequence, 1, 0, 0),
  [331] = {.entry = {.count = 1, .reusable = true}}, SHIFT(83),
  [333] = {.entry = {.count = 1, .reusable = true}}, SHIFT(84),
  [335] = {.entry = {.count = 1, .reusable = true}}, SHIFT(85),
  [337] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_hexdigit, 1, 0, 1),
  [339] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_hexdigit, 1, 0, 2),
  [341] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_hexdigit, 1, 0, 0),
  [343] = {.entry = {.count = 1, .reusable = true}}, SHIFT(89),
  [345] = {.entry = {.count = 1, .reusable = true}}, SHIFT(90),
  [347] = {.entry = {.count = 1, .reusable = true}}, SHIFT(91),
  [349] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [351] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [353] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_hexdigit, 1, 0, 2),
  [355] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_hexdigit, 1, 0, 0),
  [357] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_arguments_repeat1, 2, 0, 0),
  [359] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_arguments_repeat1, 2, 0, 0), SHIFT_REPEAT(3),
  [362] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [364] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [366] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_hexdigit, 1, 0, 1),
  [368] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_namedargexpression, 4, 0, 0),
  [370] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_argexpression, 1, 0, 0),
  [372] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [374] = {.entry = {.count = 1, .reusable = true}}, SHIFT(113),
  [376] = {.entry = {.count = 1, .reusable = true}}, SHIFT(87),
  [378] = {.entry = {.count = 1, .reusable = true}}, SHIFT(110),
  [380] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [382] = {.entry = {.count = 1, .reusable = true}}, SHIFT(74),
  [384] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_gosu(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
